// A robust collection of 5th-grade spelling challenges
const spellingBee2026 = [
    "ability",
    "always",
    "animals",
    "already",
    "balloon",
    "because",
    "birthday",
    "boring",
    "brown",
    "carpet",
    "cheese",
    "clear",
    "close",
    "clothes",
    "cloud",
    "coat",
    "computer",
    "crown",
    "decimal",
    "dessert",
    "digit",
    "doctor",
    "does",
    "dollar",
    "dream",
    "dried",
    "earth",
    "equal",
    "everyone",
    "example",
    "farther",
    "fellow",
    "forty",
    "forward",
    "friend",
    "globe",
    "gorilla",
    "grandma",
    "gravy",
    "greater",
    "hatch",
    "high",
    "history",
    "humor",
    "icon",
    "insect",
    "itch",
    "item",
    "judge",
    "knee",
    "learning",
    "leave",
    "logic",
    "loose",
    "market",
    "marvel",
    "method",
    "minute",
    "modern",
    "necklace",
    "next",
    "ninth",
    "nothing",
    "often",
    "opponent",
    "panic",
    "parade",
    "peanut",
    "planet",
    "poetry",
    "popular",
    "proof",
    "purple",
    "purse",
    "quarter",
    "quiz",
    "really",
    "reward",
    "right",
    "rumor",
    "said",
    "school",
    "sign",
    "solve",
    "square",
    "stretch",
    "surface",
    "surprise",
    "tattoo",
    "through",
    "tight",
    "tomorrow",
    "tonight",
    "tractor",
    "twice",
    "uniform",
    "until",
    "vacation",
    "village",
    "volts",
    "weird",
    "witness",
    "action",
    "feature",
    "process",
    "aspire",
    "activity",
    "fiction",
    "promise",
    "available",
    "alert",
    "fifteen",
    "property",
    "battle",
    "apologize",
    "gentle",
    "provide",
    "beauty",
    "athletic",
    "ginger",
    "quality",
    "biscuit",
    "awesome",
    "gravity",
    "raise",
    "brief",
    "banners",
    "growth",
    "receive",
    "bruise",
    "beaver",
    "guard",
    "referred",
    "capable",
    "billion",
    "hexagon",
    "regular",
    "cellular",
    "breakfast",
    "honest",
    "religion",
    "choice",
    "build",
    "hornet",
    "sauce",
    "comfortable",
    "carnival",
    "hospital",
    "session",
    "compliment",
    "castle",
    "ignore",
    "shield",
    "consonant",
    "charge",
    "illegal",
    "similar",
    "council",
    "cheap",
    "invite",
    "solution",
    "country",
    "consider",
    "join",
    "station",
    "curious",
    "cousin",
    "keyboard",
    "surgery",
    "debut",
    "creaking",
    "lecture",
    "system",
    "decision",
    "culture",
    "leopard",
    "taught",
    "design",
    "cycle",
    "lovely",
    "together",
    "desperate",
    "decide",
    "major",
    "traffic",
    "diagram",
    "diary",
    "measure",
    "traveled",
    "difference",
    "different",
    "mention",
    "trophy",
    "disease",
    "discussion",
    "muscle",
    "twelfth",
    "echo",
    "division",
    "musicians",
    "ultimate",
    "employee",
    "double",
    "navy",
    "urgent",
    "enough",
    "downstairs",
    "negative",
    "visible",
    "errands",
    "earthquake",
    "noise",
    "voyage",
    "February",
    "electrical",
    "observe",
    "weapon",
    "finance",
    "enemy",
    "package",
    "whom",
    "fracture",
    "estimation",
    "painful",
    "funnel",
    "excuse",
    "pasture",
    "geologist",
    "factory",
    "plastic",
    "favorite",
    "practice",
    "arrive",
    "gesture",
    "graduate",
    "ache",
    "amendment",
    "annual",
    "grease",
    "grief",
    "haunt",
    "health",
    "horrible",
    "hourly",
    "imagine",
    "increase",
    "injury",
    "instead",
    "juice",
    "knuckle",
    "laughter",
    "laundry",
    "loathe",
    "material",
    "miserable",
    "moisture",
    "multiplication",
    "natural",
    "nauseous",
    "neighbor",
    "obvious",
    "occurred",
    "patience",
    "pause",
    "permission",
    "pharmacy",
    "physics",
    "pleasant",
    "poison",
    "portion",
    "previous",
    "purchase",
    "quote",
    "reasonable",
    "receipt",
    "responsible",
    "rhyme",
    "ritual",
    "sculpture",
    "sincerely",
    "social",
    "straight",
    "structure",
    "suffered",
    "syllable",
    "temperature",
    "testimony",
    "theory",
    "thought",
    "tissue",
    "treasure",
    "triumph",
    "umbrella",
    "valuable",
    "villain",
    "whose",
    "wrinkle",
];
let speech = new SpeechSynthesisUtterance();
let btn = document.getElementById("btn");
let correctBtn = document.getElementById("correct");
let incorrectBtn = document.getElementById("incorrect");
let wordText = document.getElementById("word");
let replayAudioBtn = document.getElementById("replay");

let currentWord = "";

btn.onclick = () => {
    speech.volume = 1;
    speech.rate = 1;
    speech.pitch = 1;

    let wordID = Math.floor(Math.random() * spellingBee2026.length);

    currentWord = spellingBee2026[wordID];

    wordText.textContent = currentWord;
    wordText.style.color = "black";
    speech.text = currentWord;

    window.speechSynthesis.speak(speech);
};

correctBtn.onclick = () => {
    wordText.style.color = "green";
    let correctSound = new Audio("correct.mp3");
    correctSound.play();
};

incorrectBtn.onclick = () => {
    wordText.style.color = "red";
    let wrongSound = new Audio("wrong.mp3");
    wrongSound.play();
};

replayAudioBtn.onclick = () => {
    if (currentWord !== "") {
        speech.text = currentWord;
        window.speechSynthesis.speak(speech);
    } else {
        console.log("No word has been selected yet! Click the start button first.");
    }
};

document.getElementById("thisonething").innerText = spellingBee2026.join("\n");

// ... (your existing array and variables)

const toggleBtn = document.getElementById("toggleBtn");
const wordListDisplay = document.getElementById("thisonething");

// 1. Fill the list but keep it hidden initially
// Using .join('<br>') puts every word on its own line!
wordListDisplay.innerHTML = spellingBee2026.join("<br>");

// 2. The Toggle Logic
toggleBtn.onclick = () => {
    if (wordListDisplay.style.display === "none") {
        wordListDisplay.style.display = "block";
        toggleBtn.innerText = "Hide Word List";
        toggleBtn.classList.replace("btn-secondary", "btn-dark");
    } else {
        wordListDisplay.style.display = "none";
        toggleBtn.innerText = "Show Word List";
        toggleBtn.classList.replace("btn-dark", "btn-secondary");
    }
};
